version: '2'
services:
  php:
    # build a custom image
    build:
      context: .
      dockerfile: php.dockerfile
    environment:
      POSTGRES_DB: example
      POSTGRES_USER: example
      POSTGRES_PASSWORD: example
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - '8000:80'
    networks:
      - example

  db:
    image: postgres
    restart: always
    hostname: db
    environment:
      POSTGRES_DB: example
      POSTGRES_USER: example
      POSTGRES_PASSWORD: example
    ports:
      - '5432:5432'
    networks:
      - example

  db_test:
    image: postgres
    restart: always
    hostname: db_test
    environment:
      POSTGRES_DB: example
      POSTGRES_USER: example
      POSTGRES_PASSWORD: example
    networks:
      - example

networks:
  example: